sudo: required

language: node_js

node_js:
  - '10'

stages:
  - test
  - name: deploy
    if: (NOT type IN (pull_request)) AND (branch = master)
  - name: release
    if: (NOT type IN (pull_request)) AND (branch = master)

jobs:
  include:
    - stage: test
      script: npm install && npm run test
    - stage: deploy
      script: npm install && npm run build
      deploy:
        provider: pages
        local-dir: dist
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
    - stage: release
      if: branch = master
      script: npm install && npm run build && npx semantic-release
