sudo: required

language: node_js

node_js:
  - '10'

stages:
  - build
  - test
  - name: release
    if: (branch = master) AND (NOT (type IN (push, pull_request)))
  - name: deploy
    if: (branch = master) AND (NOT (type IN (push, pull_request)))

jobs:
  include:
    - stage: build
      script: npm install
      script: npm run build
    - stage: test
      script: npm run test
    - stage: release
      if: branch = master
      script: npx semantic-release
    - stage: deploy
      script: skip # to not run Travis' default script
      deploy:
        provider: pages
        local-dir: dist
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
