sudo: required

language: node_js

node_js:
  - '10'

stages:
  - compile
  - test
  - release
  - deploy

jobs:
  include:
    - name: compile
      script: npm install
      script: npm run build
    - name: test
      script: npm run test
    - name: release
      script: npx semantic-release
    - name: deploy
      deploy:
      provider: pages
      local-dir: dist
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      on:
        branch: master