sudo: required

language: node_js

node_js:
  - '10'

stages:
  - compile
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - name: compile
      script: npm install
      script: npm run build
    - name: test
      script: npm run test
    - name: deploy
      script: npx semantic-release
      script: npm run deploy:demo
